# Generated by Django 3.0 on 2021-08-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210810_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
