# Generated by Django 3.0 on 2021-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210830_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(default=False, upload_to='video/%y'),
        ),
    ]
