# Generated by Django 3.0 on 2021-09-02 15:17

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210902_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(default=False, null=True, upload_to=chat.models.upload_image_to),
        ),
    ]
