# Generated by Django 3.0 on 2021-09-27 13:07

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20210903_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, default=False, null=True, upload_to=chat.models.upload_video_to),
        ),
    ]
