# Generated by Django 3.0 on 2021-09-27 13:33

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20210927_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, default=False, null=True, upload_to=chat.models.upload_image_to),
        ),
    ]
