# Generated by Django 3.0 on 2021-08-30 17:41

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(null=True, upload_to=chat.models.upload_image_to),
        ),
    ]
