# Generated by Django 3.0 on 2021-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(default=False, null=True, upload_to='message_media/%y'),
        ),
    ]
