# Generated by Django 3.0 on 2021-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210901_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(default=False, upload_to='message_media/%y'),
        ),
    ]
