# Generated by Django 3.0 on 2021-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20210901_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(default=False, upload_to='media/message_media/%y'),
        ),
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(default=False, upload_to='media/video/%y'),
        ),
    ]
