# Generated by Django 3.0 on 2021-09-02 07:27

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210902_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, default=False, upload_to=chat.models.upload_image_to),
        ),
    ]
