# Generated by Django 3.0 on 2021-08-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
